### ISSUE TITLE
Support for protolint

### ISSUE THREAD

**Issue by jpreese** [uber/prototool#473] opened 2019-07-09 02:23 UTC
As requested in #454 I would like to see https://github.com/yoheimuta/protolint incorporated to handle custom linting rules. 

The maintainer is incredibly active, and already has a couple code editor extensions built around it (e.g. https://github.com/plexsystems/vscode-protolint)

**Comment by smaye81** [comment] 2019-07-09 17:02
Protolint is largely a copy/paste of Prototool's codebase - the author has taken steps to change this recently (please check it out for yourself) but the core still stands. 

As a result, Prototool covers almost all functionality that Protolint does by design.  It's an entirely separate product and seems to provide the functionality you're looking for, so I'm not sure what there is to incorporate into Prototool.   I’m guessing you mean to be able to dynamically add custom linting rules (which isn’t a feature of Protolint either), but my previous comment on https://github.com/uber/prototool/issues/454 was more aimed at adding an additional linter to Prototool, not adding the ability to provide custom linting rules.

**Comment by smaye81** [comment] 2019-07-10 13:53
Going to close this issue, but if there is an additional linter, you'd like added, please re-open a new issue.

**Closed by smaye81** 2019-07-10 13:53 UTC
