### ISSUE TITLE
windows binary

### ISSUE THREAD

**Issue by jorgheymans** [uber/prototool#36] opened 2018-04-19 12:53 UTC
Any chance to produce a windows binary as well ?

**Comment by peter-edge** [comment] 2018-04-19 12:58
Duplicate of https://github.com/uber/prototool/issues/9, there’s some work to do first.

**Closed by peter-edge** 2018-04-19 12:58 UTC

**Comment by jorgheymans** [comment] 2018-04-19 13:02
thanks, i had seen that issue but did not realize it's aiming for the same thing

**Comment by peter-edge** [comment] 2018-08-07 07:47
@jorgheymans can you check out the `windows` branch #177 and see if it works?

**Comment by jorgheymans** [comment] 2018-08-17 08:01
@peter-edge just got back from holidays, is there something to test still ?

**Comment by peter-edge** [comment] 2018-08-17 10:39
If you check out the `windows` branch and do `make install`, you can see if it works, and let us know in #9 what the issues are. Alternatively, you can just keep on working on the `windows` branch in a fork to make it work including with AppVeyor, and send us a PR :-)
